### ISSUE TITLE
如何限制图片上传最多张数？

### ISSUE THREAD

**Issue by senyouv** [tangshuang/HHuploadify#3]
看来您的推介文章中截图示例有“最多7张”的限制字样，但是在源码中没找到，请问怎么设置呢？
另外，我把auto设置成false为啥还是自动上传了。。。

**Comment by tangshuang** [comment]
有一个onSelect，你可以在传给它的函数里面做一些判断来移除多余的图片。
auto这个问题我还没有遇到过，你可以给个case吗？

**Comment by heroes7** [comment]
@senyouv  小哥，如何限制？能否贴个代码看看  非常感谢
